# load-bal.yaml
apiVersion: v1
kind: Service
metadata:
  name: load-bal
spec:
  type: LoadBalancer  # 타입 LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30088   # 30088로 변경
  selector:
    run: load-bal
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: load-bal
  name: load-bal
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80