# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-viewer
  namespace: default
rules:
- apiGroups: [""] # ""은 core API group을 나타냅니다.
  resources: 
  - pods
  verbs: 
  - get
  - watch
  - list