# minio-instance.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
type: Opaque
data:
  accesskey: bWluaW8=      # minio
  secretkey: bWluaW8xMjM=  # minio123
---
# MinIO Service 리소스
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio-dev
---
# MinIO 사용자 정의 리소스
apiVersion: operator.min.io/v1
kind: MinIOInstance
metadata:
  name: minio-dev
spec:
  metadata:
    labels:
      app: minio-dev
    annotations:
      prometheus.io/path: /minio/prometheus/metrics
      prometheus.io/port: "9000"
      prometheus.io/scrape: "true"
  image: minio/minio:RELEASE.2020-06-03T22-13-49Z
  serviceName: minio-internal-service
  zones:
    - name: "zone-0"
      servers: 1
  volumesPerServer: 1
  mountPath: /export
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  credsSecret:
    name: minio-creds-secret
  podManagementPolicy: Parallel
  requestAutoCert: false
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 60
  readiness:
    initialDelaySeconds: 120
    periodSeconds: 60