# mypod-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mypods.crd.example.com
spec:
  group: crd.example.com
  version: v1
  scope: Namespaced
  names:
    plural: mypods   # 복수 이름
    singular: mypod  # 단수 이름
    kind: MyPod      # Kind 이름
    shortNames:      # 축약 이름
    - mp